[package]
name = "xrp"
version = "0.1.0"
edition = "2021"

[features]
default = []
gui = ["eframe", "egui", "env_logger"]
nt = []


[dependencies]
eframe = {version = "0.31.1", optional = true}
egui = {version = "0.31.1", optional = true}
env_logger = {version = "0.11.8", optional = true}
# nt4_rs = {git = "https://github.com/JaciBrunning/robot.rs", package = "nt4_rs"}

once_cell = "1.21.3"

