[package]
name = "xrp"
version = "0.1.0"
edition = "2021"

[features]
default = []
gui = ["macroquad"]

[dependencies]
lazy_static = "1.5.0"
macroquad = { version = "0.4.13", optional = true }
once_cell = "1.20.3"
